/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MiddleboxServer_constants.h"

namespace MiddleBoxServer {

const MiddleboxServerConstants g_MiddleboxServer_constants;

MiddleboxServerConstants::MiddleboxServerConstants() {
}

} // namespace

