/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef GatewayServer_CONSTANTS_H
#define GatewayServer_CONSTANTS_H

#include "GatewayServer_types.h"

namespace GatewayServer {

class GatewayServerConstants {
 public:
  GatewayServerConstants();

};

extern const GatewayServerConstants g_GatewayServer_constants;

} // namespace

#endif
