/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MiddleboxServer_CONSTANTS_H
#define MiddleboxServer_CONSTANTS_H

#include "MiddleboxServer_types.h"

namespace MiddleBoxServer {

class MiddleboxServerConstants {
 public:
  MiddleboxServerConstants();

};

extern const MiddleboxServerConstants g_MiddleboxServer_constants;

} // namespace

#endif
