// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "TMiddleBoxService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TThreadedServer.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

#include "TMiddleBoxServiceHandler.h"

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;


using namespace  ::MiddleBoxServer;

int main(int argc, char **argv) {
  int port = 9090;
  boost::shared_ptr<TMiddleBoxServiceHandler> handler(new TMiddleBoxServiceHandler());
  boost::shared_ptr<TProcessor> processor(new TMiddleBoxServiceProcessor(handler));
  boost::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  boost::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  boost::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TThreadedServer server(processor, serverTransport, transportFactory, protocolFactory);

  if (handler->Init(argc, argv) != true) 
  {
	  return -1;
  }

  try
  {
	  server.serve();
  }
  catch (TException& tx) {
	  cout << "ERROR: " << tx.what() << endl;
  }

  return 0;
}
